navikt/k9-selvbetjening-oppslag

build.gradle.kts, src/main/kotlin/no/nav/k9/inngaende/oppslag/BarnOppslag.kt, src/main/kotlin/no/nav/k9/utgaende/rest/TpsProxyV1.kt, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/TestConfiguration.kt, src/test/kotlin/no/nav/k9/wiremocks/AktoerRegisterResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/TpsProxyBarnResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/TpsProxyResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/WireMockStubs.kt
Merges etter feature-AppTest, som branchen er basert på.
=> Feature app test barn

src/main/kotlin/no/nav/k9/inngaende/oppslag/ArbeidsgivereOppslag.kt, src/main/kotlin/no/nav/k9/utgaende/rest/RestUtils.kt, src/main/kotlin/no/nav/k9/utgaende/rest/TpsProxyV1.kt, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/wiremocks/ArbeidstakerResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/EnhetsregResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/TpsProxyBarnResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/TpsProxyResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/WireMockStubs.kt
Skal inn etter feature-AppTestArbeidsgiver
=> Feature ikke returner tomt mellomnavn

src/main/kotlin/no/nav/k9/utgaende/rest/RestUtils.kt, src/main/kotlin/no/nav/k9/utgaende/rest/TpsProxyV1.kt, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/wiremocks/ArbeidstakerResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/TpsProxyBarnResponseTransformer.kt
basert på branch feature-ikkeReturnerTomtMellomnavn. Review derfor den først.
=> Test edge cases

build.gradle.kts, src/main/kotlin/no/nav/k9/utgaende/gateway/BrregProxyV1Gateway.kt, src/main/kotlin/no/nav/k9/utgaende/gateway/MetricsFriendly.kt, src/test/kotlin/no/nav/k9/utgaende/gateway/MetricsFriendlyTest.kt
=> Metrics på roller fra Brønnøysund

build.gradle.kts, src/main/kotlin/no/nav/k9/SelvbetjeningOppslag.kt, src/main/kotlin/no/nav/k9/utgaende/rest/AktoerregisterV1.kt, src/main/kotlin/no/nav/k9/utgaende/rest/ArbeidsgiverOgArbeidstakerRegisterV1.kt, src/main/kotlin/no/nav/k9/utgaende/rest/BrregProxyV1.kt, src/main/kotlin/no/nav/k9/utgaende/rest/EnhetsregisterV1.kt, src/main/kotlin/no/nav/k9/utgaende/rest/NaisStsAccessTokenClient.kt, src/main/kotlin/no/nav/k9/utgaende/rest/RestUtils.kt, src/main/kotlin/no/nav/k9/utgaende/rest/TpsProxyV1.kt, src/test/kotlin/no/nav/k9/inngaende/oppslag/PersonligeForetakOppslagTest.kt
Konverterer logging av url til urlTemplate for å skjule mulige person/stedslokaliserende data i url-er.
=> Oppgraderer dusseldorf-ktor og logger kun urlTemplate.

.github/workflows/build-and-deploy.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/test/kotlin/no/nav/k9/utgaende/gateway/MetricsFriendlyTest.kt
Oppdaterer avhengigheter og actions.
Ekskluderer  "kotlin-test-junit") fordi Gradle trekker dette inn selv og da blir det kræsj. Ref https://github.com/gradle/gradle/issues/17137 og https://youtrack.jetbrains.com/issue/KT-46090
Closes #60 
Closes #59 
Closes #57 
Closes #56 
Closes #51 
Closes #46
=> Oppdatere avhengigheter

nais/dev-fss.json, nais/naiserator.yml, nais/prod-fss.json
Plukker opp secrets direkte fra kubernetes secrets.
=> Migrere til eget namespace

src/main/kotlin/no/nav/k9/inngaende/oppslag/ArbeidsgivereOppslag.kt, src/main/kotlin/no/nav/k9/inngaende/oppslag/OppslagService.kt, src/main/kotlin/no/nav/k9/utgaende/gateway/ArbeidsgiverOgArbeidstakerRegisterV1Gateway.kt, src/main/kotlin/no/nav/k9/utgaende/rest/ArbeidsgiverOgArbeidstakerRegisterV1.kt, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/FødselsnummerOversikt.kt, src/test/kotlin/no/nav/k9/wiremocks/ArbeidstakerResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/PdlAktoerIdResponseTransformer.kt
Refaktorerer til å forholde oss til Arbeidsgivere og ikke Arbeidsforhold.
Legger til test som verifiserer.
Før endring:
Etter endring:
=> Fjerner duplikate arbeidsgivere som forekommer dersom man har flere ulike arbeidsforhold hos samme arbeidsgiver.

.github/workflows/apply-alerts.yml, .github/workflows/build-and-deploy.yml, .github/workflows/snyk.yml, build.gradle.kts
* Closes #110
* Closes #109
* Closes #108
* Closes #101
=> Oppdatere pakker

.github/workflows/apply-alerts.yml, .github/workflows/build-and-deploy.yml, .github/workflows/snyk.yml, Dockerfile, build.gradle.kts
- closes #121
- closes #120
- closes #119
=> Oppgraderer actions, plugins, dependencies og Java.

.github/workflows/apply-alerts.yml, .github/workflows/build-and-deploy.yml, nais/dev-fss.json, nais/prod-fss.json, src/main/kotlin/no/nav/k9/Configuration.kt, src/main/kotlin/no/nav/k9/SelvbetjeningOppslag.kt, src/main/kotlin/no/nav/k9/utgaende/auth/AccessTokenClientResolver.kt, src/main/kotlin/no/nav/k9/utgaende/rest/ArbeidsgiverOgArbeidstakerRegisterV1.kt, src/main/resources/application.conf, src/test/kotlin/no/nav/k9/TestConfiguration.kt
Ny ingress for aareg og ereg.
Oppdaterer actions
* Closes https://github.com/navikt/k9-selvbetjening-oppslag/pull/123
* Closes https://github.com/navikt/k9-selvbetjening-oppslag/pull/124
=> Tokenx mot aareg

Dockerfile
Snyk UI kjenner til imaget, og den er uten kjente sårbarheter pr.dd.
=> Bytter baseimage til Amazon Corretto 17-Alpine

.github/workflows/build-and-deploy.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
- closes #136
- closes #133
- closes #129
- closes #128
- closes #126
- closes #113
=> Oppdaterer gradle wrapper, pakker, plugins og actions.

build.gradle.kts
=> Oppgraderer sifTilgangskontroll med sårbarhetsfiks.

nais/dev-gcp.json, nais/prod-gcp.json, src/main/kotlin/no/nav/k9/Configuration.kt, src/main/kotlin/no/nav/k9/SelvbetjeningOppslag.kt, src/main/kotlin/no/nav/k9/inngaende/oppslag/OppslagService.kt, src/main/kotlin/no/nav/k9/utgaende/gateway/ArbeidsgiverOgArbeidstakerRegisterV1Gateway.kt, src/main/kotlin/no/nav/k9/utgaende/rest/ArbeidsgiverOgArbeidstakerRegisterV1.kt, src/main/kotlin/no/nav/k9/utgaende/rest/ArbeidsgiverOgArbeidstakerRegisterV2.kt, src/main/kotlin/no/nav/k9/utgaende/rest/aaregv2/ArbeidsforholdStatus.kt, src/main/kotlin/no/nav/k9/utgaende/rest/aaregv2/ArbeidsgiverOgArbeidstakerRegisterV2.kt, src/main/kotlin/no/nav/k9/utgaende/rest/aaregv2/JsonUtils.kt, src/main/resources/application.conf, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/ApplicationWithMocks.kt, src/test/kotlin/no/nav/k9/TestConfiguration.kt, src/test/kotlin/no/nav/k9/wiremocks/ArbeidstakerResponseV2Transformer.kt, src/test/kotlin/no/nav/k9/wiremocks/WireMockStubs.kt
Beholder oppslag til v1 og returnerer det resultatet. Slår samtidig opp til v2 og sammenligner responsen. Logger om det er likt eller ei.
=> "Skyggemigrering" til aareg v2

.github/workflows/build-and-deploy.yml, build.gradle.kts
- closes #159
- closes #157
- closes #155
- closes #154
- closes #152
- closes #149
- opgraderer sif-tilgangskontroll.
=> Oppgraderer pakker, plugins og actions.

build.gradle.kts
* Closes #164
* Closes #162
* Closes #161
=> Oppdatere pakker.

build.gradle.kts, nais/dev-gcp.json, nais/naiserator.yml, nais/prod-gcp.json
Oppdaterer pakker. 
Closes #175 
Closes #174
=> Fjerner ingress og gamle apper fra acl

build.gradle.kts, src/main/kotlin/no/nav/k9/inngaende/oppslag/BarnOppslag.kt, src/main/kotlin/no/nav/k9/inngaende/oppslag/MegOppslag.kt, src/main/kotlin/no/nav/k9/inngaende/oppslag/SystemOppslagService.kt, src/test/kotlin/no/nav/k9/ApplicationTest.kt, src/test/kotlin/no/nav/k9/wiremocks/PDLHentBarnResponseTransformer.kt, src/test/kotlin/no/nav/k9/wiremocks/PDLPersonResponseTransformer.kt
- Oppdaterer foedsel med foedselsdato
- Fjerner ubrukt forkortetNavn.
=> Bumper sif-tilgangskontroll til 5.0.0

build.gradle.kts
=> Bumper pakker og plugins.
